### ISSUE TITLE
Interest in implementing a master password?

### ISSUE THREAD

**Issue by ericonr** [noocsharp/npm#3]
I realize that's likely to be way more complicated, but I feel like having to type out the same password repeatedly for each and every service can be a bit error prone and tiring. Do you have any plans to implement a master password or is that entirely out of scope?

**Comment by noocsharp** [comment]
The idea is that a password "repository" will have a single master password which is used to encrypt every password it contains.
`npm-agent` can then cache this master password for a period of time so it doesn't need to be entered all the time. The `npm` program (which should now be usable) is used to manage this repository.
