### ISSUE TITLE
EOF does not necessarily indicate a failure in get_password

### ISSUE THREAD

**Issue by ioraff** [noocsharp/npm#4]
Re: https://github.com/noocsharp/npm/blob/864d47a2faa044046189ed76b0c5d7aa0da96d50/util.c#L32-L33

For instance, unlike `bemenu`, `dmenu-wl` does not append a newline to its output.

**Comment by noocsharp** [comment]
Fair enough, but I use `bemenu` and I'm pretty sure I'm the only serious user of `npm`, so for other password entry programs, send a patch to fix any problems that come up.

**Comment by noocsharp** [comment]
Fixed, we treat the EOF as the end and trim final newline if there is one.
